name: first
on: [pull_request, push]
jobs:
  job1:
    name: Get Current Date
    runs-on: ubuntu-latest
    steps:
      - name: step one 1
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: step two 2
        run: env|sort
  job2:
    name: Second job 2git add
    runs-on: windows-latest
    steps:
      - name: step one 1 1
        uses: actions/checkout@v2
  job3:
    needs: [ job2, job1]
    name: Third job
    runs-on: macos-latest
    steps:
      - name: Third
        uses: actions/checkout@v1
  job4:
    needs: [ job2, job1, job3 ]
    name: Third job
    runs-on: macos-latest
    steps:
      - name: Third
        uses: actions/checkout@v1
