name: first
on: [pull_request, push]
jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
      - name: step one 1
        uses: actions/checkout@v2
      - name: step two 2
        run: env|sort
  Job2:
    name: Second job
    runs-on: windows-latest
    steps:
      - name: step one 1 1
        uses: actions/checkout@v2
      - name: step two 2 2
        run: "\Get-ChildItem Env:| Sort Object Name"
