name: first
on: [pull_request, push]
jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
      - name: step one 1
        uses: actions/checkout@v2
      - name: step two 2
        run: env|sort
  job2:
    name: Second job 2git add
    runs-on: windows-latest
    steps:
      - name: step one 1 1
        uses: actions/checkout@v2
  job3:
    name: Third job
    needs: [ job2, job1]
    runs-on: ubuntu-latest
